main/urls.py
from django.contrib import admin
from django.urls import path
from main import views

condition = True


def the_url():
    if condition:
        return path('', views.base)


app_name = 'main'
urlpatterns = [
    path('', views.base),
    path('section/<str:slug>/', views.section, name='section'),
    path('section/<str:slug>/<str:post_slug>/', views.post_details, name='details'),
    path('section/<str:slug>/gallery/<int:pk>/', views.gallery_details, name='gallery_details'),
    path('gallery1/', views.gallery1, name='gallery1'),
    path('gallery2/', views.gallery2, name='gallery2'),
    path('gallery3/', views.gallery3, name='gallery3'),
    path('test/', views.testing_post, name='testing_post'),
    path('post1/', views.post1, name='post1'),
    path('post2/', views.post2, name='post2'),
    path('post3/', views.post3, name='post3'),

]

# path('<str:slug_post>/', posts_views.details, name='details'),

mini_web_creator_final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views.py
from django.shortcuts import render, get_object_or_404, redirect, Http404
from .models import Section, TextSection, Text, SidePostSection, SidePost, \
    PostSection, Post, PostImage, Carousel, CarouselImage, GallerySection, Gallery, GalleryImage, NavigationBar, \
    BackgroundImage, Instruction, ImageSection, Image, InfoTab

numbers = []
for _ in range(25):
    numbers.append(_)


# Create your views here.
def base(request):
    sections = Section.objects.all()
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()
    if (Instruction.objects.first() is None or Instruction.objects.first().On is False) and Section.objects.all():
        home_url = Section.objects.first().slug
    else:
        home_url = False

    context = {
        'home_url': home_url,
        'sections': sections,
        'navigation_bar': navigation_bar,
        'background_image': background_image,
    }
    if home_url:
        return redirect(f'/section/{home_url}')
    else:
        return render(request, 'main/base.html', context)


def section(request, slug):
    # ----------------section
    sections = Section.objects.all()
    current_section = get_object_or_404(Section, slug=slug)

    # --------------text
    text_sections = TextSection.objects.all()
    text = Text.objects.all()

    # --------------side_post
    side_post_sections = SidePostSection.objects.all()
    side_posts = SidePost.objects.all()

    # --------------posts
    post_sections = PostSection.objects.all()
    posts = Post.objects.all()

    # --------------carousels
    carousels = Carousel.objects.all()
    carousel_images = CarouselImage.objects.all()
    carousel_text_style = "color: white; text-shadow: black 0.1em 0.1em 0.2em"

    # --------------gallery
    gallery_sections = GallerySection.objects.all()
    galleries = Gallery.objects.all()

    # --------------navigation bar
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()
    # --------------images
    image_section = ImageSection.objects.all()
    images = Image.objects.all()

    # -----------------info tab
    info_tab = InfoTab.objects.all()
    context = {
        'sections': sections,
        'text_sections': text_sections,
        'text': text,
        'numbers': numbers,
        'current_section': current_section,
        'side_post_sections': side_post_sections,
        'side_posts': side_posts,
        'post_sections': post_sections,
        'posts': posts,
        'carousels': carousels,
        'carousel_images': carousel_images,
        'carousel_text_style': carousel_text_style,
        'gallery_sections': gallery_sections,
        'galleries': galleries,
        'navigation_bar': navigation_bar,
        'background_image': background_image,
        'image_section': image_section,
        'images': images,
        'info_tabs': info_tab,

    }
    return render(request, 'main/section.html', context)


def post_details(request, slug, post_slug):
    current_post = get_object_or_404(Post, post_slug=post_slug)
    current_section = get_object_or_404(Section, slug=slug)
    navigation_bar = NavigationBar.objects.first()
    sections = Section.objects.all()
    background_image = BackgroundImage.objects.first()
    images = PostImage.objects.all()
    context = {
        'navigation_bar': navigation_bar,
        'current_section': current_section,
        'current_post': current_post,
        'sections': sections,
        'background_image': background_image,
        'images': images,

    }
    return render(request, 'posts/details.html', context)


def gallery_details(request, slug, pk):
    gallery_section = GallerySection.objects.all()
    sections = Section.objects.all()
    filter_section = get_object_or_404(Gallery, pk=pk)
    images = GalleryImage.objects.filter(section=filter_section)
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()

    context = {
        'navigation_bar': navigation_bar,
        'gallery_section': gallery_section,
        'current_section': get_object_or_404(Section, slug=slug),
        'sections': sections,
        'gallery': section,
        'images': images,
        'background_image': background_image,

    }
    return render(request, 'gallery/gallery_details.html', context)


def gallery1(request):
    sections = Section.objects.all()
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()

    context = {
        'sections': sections,
        'navigation_bar': navigation_bar,
        'background_image': background_image,
    }
    if (Instruction.objects.first() is None or Instruction.objects.first().On is False) and Section.objects.all():
        return Http404()
    else:
        return render(request, 'main/gallery_detail/gallery1.html', context)


def gallery2(request):
    sections = Section.objects.all()
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()

    context = {
        'sections': sections,
        'navigation_bar': navigation_bar,
        'background_image': background_image,
    }

    if (Instruction.objects.first() is None or Instruction.objects.first().On is False) and Section.objects.all():
        return Http404()
    else:
        return render(request, 'main/gallery_detail/gallery2.html', context)


def gallery3(request):
    sections = Section.objects.all()
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()

    context = {
        'sections': sections,
        'navigation_bar': navigation_bar,
        'background_image': background_image,
    }

    if (Instruction.objects.first() is None or Instruction.objects.first().On is False) and Section.objects.all():
        return Http404()
    else:
        return render(request, 'main/gallery_detail/gallery3.html', context)


def post1(request):
    sections = Section.objects.all()
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()

    context = {
        'sections': sections,
        'navigation_bar': navigation_bar,
        'background_image': background_image,
    }

    if (Instruction.objects.first() is None or Instruction.objects.first().On is False) and Section.objects.all():
        return Http404()
    else:
        return render(request, 'main/post_detail/post1.html', context)


def post2(request):
    sections = Section.objects.all()
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()

    context = {
        'sections': sections,
        'navigation_bar': navigation_bar,
        'background_image': background_image,
    }

    if (Instruction.objects.first() is None or Instruction.objects.first().On is False) and Section.objects.all():
        return Http404()
    else:
        return render(request, 'main/post_detail/post2.html', context)


def post3(request):
    sections = Section.objects.all()
    navigation_bar = NavigationBar.objects.first()
    background_image = BackgroundImage.objects.first()

    context = {
        'sections': sections,
        'navigation_bar': navigation_bar,
        'background_image': background_image,
    }

    if (Instruction.objects.first() is None or Instruction.objects.first().On is False) and Section.objects.all():
        return Http404()
    else:
        return render(request, 'main/post_detail/post3.html', context)


def testing_post(request):
    return render(request, 'test/test.html', {})

main/templates/gallery/gallery_details.html
{% extends "main/base.html" %}
{% block content %}
<div style="text-align: center"><a href="{% url 'main:section' current_section.slug %}" style="text-allign: 'center'"><button type="button" class="btn btn-light">Go Back</button></a></div>

<!--Carousel Wrapper-->
<div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">
    <!--Indicators-->
    <ol class="carousel-indicators">
    {% for image in images %}
      <li data-target="#carousel-example-1z" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.counter0 == 0 %} active {% endif %}"></li>
    {% endfor %}
    </ol>
    <!--/.Indicators-->
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
      {% for image in images %}
      <div align="center" class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
        <img class="d-block gallery-image" src="{{image.image.url}}"alt="First slide">
      </div>
      {% endfor %}
      <!--/First slide-->
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>
</div>
<div style="text-align: center"><a href="{% url 'main:section' current_section.slug %}" style="text-allign: 'center'"><button type="button" class="btn btn-light">Go Back</button></a></div>


{% endblock %}

main/templates/gallery/main_gallery.html
{% block content %}
{% for gallery_section in gallery_sections %}
    <div class="row row-cols-1 row-cols-md-3">
        {% for gallery in galleries %}
            {% if gallery_section.section == current_section and gallery_section.order == number and gallery.gallery_section == gallery_section %}
                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                      <div class="card">
                        <div class="view overlay {{ gallery_section.style }}">
                          <img class="card-img-top responsive" src="{{gallery.image.url}}" alt="" width="500" height="250">
                            <div class="overlay">
                                <h2>{{ gallery.image_title }}</h2>
                                <a class="info" href="{% url 'main:gallery_details' current_section.slug gallery.pk %}">See More</a>
                            </div>
                        </div>
                        <div class="card-body">
                          <h4 class="card-title">{{gallery.title}}</h4>
                          <p class="card-text">{{gallery.description}}</p>
                        </div>
                      </div>
                    </div>
            {% endif %}
        {% endfor %}
    </div>
{% endfor %}
{% endblock content %}